permissions:
  contents: read

env:
  RPC_URL: ${{ secrets.RPC_URL }}
  RUST_LOG: 'info,fireblocks_solana_signer=debug'
  FIREBLOCKS_ENDPOINT: ${{ vars.FIREBLOCKS_ENDPOINT }}
  FIREBLOCKS_POLL_TIMEOUT: '90'
  FIREBLOCKS_POLL_INTERVAL: '5'
  FIREBLOCKS_DEVNET: 'true'
  FIREBLOCKS_VAULT: '0'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - fireblocks
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: build
jobs:
  build:
    runs-on: ${{ vars.RUNNER }}
    name: build cli
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ubicloud/rust-cache@v2
        with:
          cache-on-failure: 'true'
          cache-all-crates: 'true'
          workspaces: |
            . -> target
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
      - uses: CarteraMesh/fireblocks-config-action@v1
        with:
          fireblocks-secret: |
            ${{ secrets.FIREBLOCKS_SECRET }}
          fireblocks-api-key: ${{ secrets.FIREBLOCKS_API_KEY }}
          fireblocks-endpoint: ${{ vars.FIREBLOCKS_ENDPOINT }}
      - name: install deps
        run: |
          sudo apt-get install -y libgpgme-dev libhidapi-dev libudev-dev
      - name: cargo build spl-token-cli solana cli
        run: |
          cargo build -p spl-token-cli
      - name: transfer
        run: |
          target/debug/spl-token transfer --fund-recipient  --with-compute-unit-limit 98401  --with-memo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"  4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU 0.00001 215r9xfTFVYcE9g3fAUGowauM84egyUvFCbSo3LKNaep
